"""Add Note model

Revision ID: 79e5ae77ec3b
Revises: 0c4772970d76
Create Date: 2026-08-17 10:56:42.786567

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '79e5ae77ec3b'
down_revision = '0c4772970d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
